// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MeshComm.Entities.Entities;

public partial class EmailLog
{
    public int EmailLogId { get; set; }
    public string RequestId { get; set; }
    public string RequestingApplication { get; set; }
    public string EmailBody { get; set; }
    public string RecipientEmail { get; set; }
    public string Cc { get; set; }
    public string Bcc { get; set; }
    public string ResponseObject { get; set; }
    public string EmailTransmissionState { get; set; }
    public bool IsActive { get; set; }
    public int CreatedBy { get; set; }
    public DateTime CreatedOn { get; set; }
    public int? UpdatedBy { get; set; }
    public DateTime? UpdatedOn { get; set; }
    public DateTime Version { get; set; }
}