// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using MeshComm.Entities.Entities;
using Microsoft.EntityFrameworkCore;

namespace MeshComm.Entities;

public partial class EmailContext : DbContext
{
    public EmailContext(DbContextOptions<EmailContext> options)
        : base(options)
    {
    }

    public virtual DbSet<EmailLog> EmailLogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<EmailLog>(entity =>
        {
            entity.HasKey(e => e.EmailLogId).HasName("PRIMARY");

            entity.ToTable("EmailLog");

            entity.Property(e => e.Bcc).HasMaxLength(1000);
            entity.Property(e => e.EmailBody)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.Cc).HasMaxLength(1000);
            entity.Property(e => e.CreatedBy).HasDefaultValueSql("'3'");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValueSql("b'1'")
                .HasColumnType("bit(1)");
            entity.Property(e => e.RecipientEmail)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.RequestId)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.RequestingApplication)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");
            entity.Property(e => e.Version)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp");
            entity.Property(e => e.ResponseObject)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.EmailTransmissionState)
                .IsRequired()
                .HasMaxLength(1000);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}